version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.7
    - 2.32.8
    - 2.32.9
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.1.2
  - dependency-name: gatsby-plugin-sass
    versions:
    - 2.8.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.0.29
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.1.6
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.1.20
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
    - 3.13.0
  - dependency-name: gatsby-plugin-typography
    versions:
    - 2.11.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.9.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
